name: ItemBlocker
version: 1.0.0
main: com.tellegram.itemblocker.ItemBlockerPlugin
author: tellegram
website: https://github.com/Tellegram/ItemBlocker
api-version: 1.20
load: POSTWORLD

commands:
  itemblock:
    description: ItemBlocker commands (reload, check, scan)
    usage: /itemblock <reload|check <ITEM>|scan <player|*>>
    aliases: [blockitem]
permissions:
  itemblocker.bypass:
    description: Bypass item blocking
    default: false
